### ISSUE TITLE
unable to test and use

### ISSUE THREAD

**Issue by laepage** [morisawa-inc/BetterOblique#1]
The filter is constantly crashing on Mac OS 10.15.7 and Glyphs 3.2-3201, have to remove it. Sorry, I was unable to catch the whole error message

**Comment by Tosche** [comment]
In my environment, the plugin returns traceback error and I am unable to try it. The crash seems to relate to beziers and pyclipper modules.

——————
BetterOblique.glyphsFilter プラグインがクラッシュを引き起こしました。プラグインマネージャーからプラグインを更新するか、元のソースから再ダウンロードしてください。

詳細：Traceback (most recent call last):

  File "plugin.py", line 14, in <module>
    from betterObliqueFilter import shear_layer

  File "betterObliqueFilter.py", line 6, in <module>
    import beziers.path

  File "__init__.py", line 6, in <module>
    from beziers.utils.booleanoperationsmixin import BooleanOperationsMixin

  File "booleanoperationsmixin.py", line 5, in <module>
    import pyclipper

ImportError: dlopen(~/Library/Application Support/Glyphs 3/Plugins/BetterOblique.glyphsFilter/Contents/Resources/site-packages/pyclipper.so, 0x0002): tried: '~/Library/Application Support/Glyphs 3/Plugins/BetterOblique.glyphsFilter/Contents/Resources/site-packages/pyclipper.so' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS~/Library/Application Support/Glyphs 3/Plugins/BetterOblique.glyphsFilter/Contents/Resources/site-packages/pyclipper.so' (no such file), '~/Library/Application Support/Glyphs 3/Plugins/BetterOblique.glyphsFilter/Contents/Resources/site-packages/pyclipper.so' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64'))

App:3.2-3202 Plugin:0.0.1-1 System:13.4.0
——————

**Comment by kosbarts** [comment]
I tried to install it on both 3.1.2 (3151) and 3.2 (3204) and the plugin is causing a crash on the launch of the app.

<img width="748" alt="Screenshot 2023-07-07 at 9 37 35 AM" src="https://github.com/morisawa-inc/BetterOblique/assets/5067985/591e640e-7278-4452-bf01-218a1e4e94ac">
<img width="652" alt="Screenshot 2023-07-07 at 9 40 27 AM" src="https://github.com/morisawa-inc/BetterOblique/assets/5067985/5b7a6553-2840-4fc1-966e-0f36104b26a8">

**Comment by takaakifuji** [comment]
@laepage @Tosche @kosbarts 
Thank you so much for the feedback! Sorry for not noticing the issue. I've included a copy of [pyclipper](https://pypi.org/project/pyclipper/) library but I took the version for Python 2. I'll make sure this will work on Glyphs 3.

**Comment by schriftgestalt** [comment]
Just got his from a user. This means that pyclipper is only available with Intel binaries but not for ARM.

```
Details:
Traceback (most recent call last):

 File "plugin.py", line 14, in <module>
   from betterObliqueFilter import shear_layer

 File "betterObliqueFilter.py", line 6, in <module>
   import beziers.path

 File "__init__.py", line 6, in <module>
   from beziers.utils.booleanoperationsmixin import BooleanOperationsMixin

 File "booleanoperationsmixin.py", line 5, in <module>
   import pyclipper

ImportError: dlopen(~/Library/Application Support/Glyphs 3/Plugins/BetterOblique.glyphsFilter/Contents/Resources/site-packages/pyclipper.so, 0x0002): tried: '~/Library/Application Support/Glyphs 3/Plugins/BetterOblique.glyphsFilter/Contents/Resources/site-packages/pyclipper.so' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS~/Library/Application Support/Glyphs 3/Plugins/BetterOblique.glyphsFilter/Contents/Resources/site-packages/pyclipper.so' (no such file), '~/Library/Application Support/Glyphs 3/Plugins/BetterOblique.glyphsFilter/Contents/Resources/site-packages/pyclipper.so' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e' or 'arm64'))

App:3.4-3414 System:15.5.0 Python:3.11 Plugin:0.0.1-1
```

**Comment by takaakifuji** [comment]
Thank you for let me know – I'm so sorry that I didn't notice this issue! This plugin is used for a multi-year project that used G2 throughout, so that would be why the test on G3 was insufficient. I'll look into it. Feature-wise I feel it should not depend on pyclipper, so I'll check again how I can handle the dependency.

**Comment by takaakifuji** [comment]
I think I've fixed this at 7343fbb. Tested on Glyphs 3.3.1 and it looks it is working for me.

Again I apologize for not being able to address this for so long!
